[build]
  command = "npm run prisma:generate"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "bcryptjs", "cors", "dotenv", "express", "helmet", "jsonwebtoken", "morgan", "multer", "serverless-http", "zod"]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true